/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author PROPERTY UNIT
 */
public class i_transfer extends javax.swing.JInternalFrame {

    /**
     * Creates new form i_transferi
     */
    public i_transfer() {
        initComponents();
        
         putClientProperty("JInternalFrame.isPalette", Boolean.TRUE);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        
        tbtn_save.setEnabled(false);
        tbtn_print.setEnabled(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        t_reference = new javax.swing.JTextField();
        t_transferto = new javax.swing.JTextField();
        t_office = new javax.swing.JTextField();
        t_datetrans = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        t_purpose = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tbtn_add = new javax.swing.JButton();
        tbtn_save = new javax.swing.JButton();
        tbtn_edit = new javax.swing.JButton();
        tbtn_clear = new javax.swing.JButton();
        tbtn_print = new javax.swing.JButton();
        tbtn_close = new javax.swing.JButton();

        setBackground(java.awt.SystemColor.activeCaption);
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 30)); // NOI18N
        jLabel1.setText("TRANSFER PROPERTY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Transfer Reference Number:");

        t_reference.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t_reference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_referenceActionPerformed(evt);
            }
        });

        t_transferto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t_transferto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_transfertoActionPerformed(evt);
            }
        });

        t_office.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t_office.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_officeActionPerformed(evt);
            }
        });

        t_purpose.setColumns(20);
        t_purpose.setRows(5);
        jScrollPane3.setViewportView(t_purpose);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Purpose:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Date Transffered:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Office:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Transfer to:");

        tbtn_add.setBackground(new java.awt.Color(255, 255, 255));
        tbtn_add.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tbtn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        tbtn_add.setText("Add");
        tbtn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn_addActionPerformed(evt);
            }
        });

        tbtn_save.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tbtn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        tbtn_save.setText("Save");

        tbtn_edit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tbtn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        tbtn_edit.setText("Edit");

        tbtn_clear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tbtn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Eraser.png"))); // NOI18N
        tbtn_clear.setText("Clear");
        tbtn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn_clearActionPerformed(evt);
            }
        });

        tbtn_print.setBackground(new java.awt.Color(255, 255, 255));
        tbtn_print.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tbtn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        tbtn_print.setText("Print");
        tbtn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn_printActionPerformed(evt);
            }
        });

        tbtn_close.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tbtn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        tbtn_close.setText("Close");
        tbtn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(14, 14, 14)
                        .addComponent(t_reference, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_datetrans, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_transferto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_office, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbtn_add)
                .addGap(2, 2, 2)
                .addComponent(tbtn_save)
                .addGap(2, 2, 2)
                .addComponent(tbtn_edit)
                .addGap(2, 2, 2)
                .addComponent(tbtn_clear)
                .addGap(2, 2, 2)
                .addComponent(tbtn_print)
                .addGap(2, 2, 2)
                .addComponent(tbtn_close)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_reference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(t_datetrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t_transferto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(t_office, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbtn_save)
                        .addComponent(tbtn_add))
                    .addComponent(tbtn_edit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbtn_close)
                        .addComponent(tbtn_clear)
                        .addComponent(tbtn_print)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clear(){
        t_datetrans.setCalendar(null);
        t_office.setText(null);
        t_transferto.setText(null);
        t_purpose.setText(null);
        t_reference.setText(null);
       
    }
    private void t_referenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_referenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_referenceActionPerformed

    private void t_transfertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_transfertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_transfertoActionPerformed

    private void t_officeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_officeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_officeActionPerformed

    private void tbtn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn_addActionPerformed
        t_reference.setEnabled(false);
        tbtn_add.setEnabled(false);
        tbtn_save.setEnabled(true);
        tbtn_edit.setEnabled(false);
     
        
         //auto increment codes
    }//GEN-LAST:event_tbtn_addActionPerformed

    private void tbtn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn_printActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtn_printActionPerformed

    private void tbtn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_tbtn_closeActionPerformed

    private void tbtn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn_clearActionPerformed
        clear();
    }//GEN-LAST:event_tbtn_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser t_datetrans;
    private javax.swing.JTextField t_office;
    private javax.swing.JTextArea t_purpose;
    private javax.swing.JTextField t_reference;
    private javax.swing.JTextField t_transferto;
    private javax.swing.JButton tbtn_add;
    private javax.swing.JButton tbtn_clear;
    private javax.swing.JButton tbtn_close;
    private javax.swing.JButton tbtn_edit;
    private javax.swing.JButton tbtn_print;
    private javax.swing.JButton tbtn_save;
    // End of variables declaration//GEN-END:variables
}
