

import frames.activity;
import frames.maintenance;
import frames.notification;
import frames.property;
import frames.search;
import frames.transfer;
import frames.unserviceable;
import frames.update;
import frames.user;

import java.awt.*;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PROPERTY UNIT
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
 
    public home() {

        initComponents();
        
        
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Rectangle bounds = ge.getMaximumWindowBounds();
            this.setMaximizedBounds(bounds);
            this.setExtendedState(MAXIMIZED_BOTH);
            
            
            btn_notification.setText("2 NOTIFICATIONS");
            desktop.updateUI();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_entry = new javax.swing.JButton();
        btn_unserviceable = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_transfer = new javax.swing.JButton();
        btn_maintenance = new javax.swing.JButton();
        btn_notification = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        btn_logs = new javax.swing.JButton();
        btn_user = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setName("Inventory System"); // NOI18N

        btn_entry.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_entry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new entry.png"))); // NOI18N
        btn_entry.setText("NEW ENTRY");
        btn_entry.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_entry.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_entry.setMinimumSize(new java.awt.Dimension(100, 100));
        btn_entry.setPreferredSize(new java.awt.Dimension(100, 100));
        btn_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entryActionPerformed(evt);
            }
        });

        btn_unserviceable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_unserviceable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/waste.png"))); // NOI18N
        btn_unserviceable.setText("UNSERVICEABLE PROPERTIES");
        btn_unserviceable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_unserviceable.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_unserviceable.setMinimumSize(new java.awt.Dimension(100, 100));
        btn_unserviceable.setPreferredSize(new java.awt.Dimension(100, 100));
        btn_unserviceable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_unserviceableActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/renew.png"))); // NOI18N
        btn_update.setText("UPDATE PROPERTY");
        btn_update.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_update.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_update.setMinimumSize(new java.awt.Dimension(100, 100));
        btn_update.setPreferredSize(new java.awt.Dimension(100, 100));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_transfer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_transfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transfer.png"))); // NOI18N
        btn_transfer.setText("TRANSFERRED PROPERTIES");
        btn_transfer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_transfer.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_transfer.setMinimumSize(new java.awt.Dimension(100, 100));
        btn_transfer.setPreferredSize(new java.awt.Dimension(100, 100));
        btn_transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transferActionPerformed(evt);
            }
        });

        btn_maintenance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_maintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/maintenance.png"))); // NOI18N
        btn_maintenance.setText("MAINTENANCE LEDGER");
        btn_maintenance.setAutoscrolls(true);
        btn_maintenance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_maintenance.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_maintenance.setMinimumSize(new java.awt.Dimension(100, 100));
        btn_maintenance.setPreferredSize(new java.awt.Dimension(100, 100));
        btn_maintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maintenanceActionPerformed(evt);
            }
        });

        btn_notification.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/notification.png"))); // NOI18N
        btn_notification.setAutoscrolls(true);
        btn_notification.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_notification.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_notification.setMinimumSize(new java.awt.Dimension(100, 100));
        btn_notification.setPreferredSize(new java.awt.Dimension(100, 100));
        btn_notification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_notificationActionPerformed(evt);
            }
        });

        btn_search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/searchfolder.png"))); // NOI18N
        btn_search.setText("SEARCH");
        btn_search.setAutoscrolls(true);
        btn_search.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_search.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_search.setMinimumSize(new java.awt.Dimension(100, 100));
        btn_search.setPreferredSize(new java.awt.Dimension(100, 100));
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_logs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_logs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logs.png"))); // NOI18N
        btn_logs.setText("ACTIVITY LOGS");
        btn_logs.setAutoscrolls(true);
        btn_logs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_logs.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_logs.setMinimumSize(new java.awt.Dimension(100, 100));
        btn_logs.setPreferredSize(new java.awt.Dimension(100, 100));
        btn_logs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logsActionPerformed(evt);
            }
        });

        btn_user.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/users.png"))); // NOI18N
        btn_user.setText("USER");
        btn_user.setAutoscrolls(true);
        btn_user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_user.setMaximumSize(new java.awt.Dimension(100, 100));
        btn_user.setMinimumSize(new java.awt.Dimension(100, 100));
        btn_user.setPreferredSize(new java.awt.Dimension(100, 100));
        btn_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_unserviceable, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addComponent(btn_maintenance, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addComponent(btn_transfer, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addComponent(btn_entry, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addComponent(btn_notification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_logs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_user, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(btn_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(btn_unserviceable, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(btn_maintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(btn_notification, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(btn_user, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(btn_logs, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        desktop.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 997, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
   
        desktop.removeAll();
        desktop.updateUI();
      try{
            update u = new update();
            desktop.add(u);
            desktop.moveToFront(u);
            u.setSize(desktop.getWidth(), desktop.getHeight());
            u.setLocation(0, 0);
            u.show();
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entryActionPerformed

        desktop.removeAll();
        desktop.updateUI();
        try{ 
            property p;
            p = new property();
            desktop.add(p);
            desktop.moveToFront(p);
            p.setSize(desktop.getWidth(), desktop.getHeight());
            p.show();
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_entryActionPerformed

    private void btn_maintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maintenanceActionPerformed
         
         desktop.removeAll();
         desktop.updateUI();
      
         try{
            maintenance m = new maintenance();
            desktop.add(m);
            desktop.moveToFront(m);
            m.setSize(desktop.getWidth(), desktop.getHeight());
            m.show();
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_maintenanceActionPerformed

    private void btn_transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transferActionPerformed
      
         desktop.removeAll();
         desktop.updateUI();
      
         try{
            transfer t = new transfer();
            desktop.add(t);
            desktop.moveToFront(t);
            t.setSize(desktop.getWidth(), desktop.getHeight());
            t.show();
        }
        catch (Exception e){
            e.printStackTrace();
        }
      
      
    }//GEN-LAST:event_btn_transferActionPerformed

    private void btn_unserviceableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_unserviceableActionPerformed
        // TODO add your handling code here:
        
         desktop.removeAll();
         desktop.updateUI();
      
         try{
            unserviceable uv = new unserviceable();
            desktop.add(uv);
            desktop.moveToFront(uv);
            uv.setSize(desktop.getWidth(), desktop.getHeight());
            uv.show();
        }
        catch (Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btn_unserviceableActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
         desktop.removeAll();
         desktop.updateUI();
      
         try{
            search s = new search();
            desktop.add(s);
            desktop.moveToFront(s);
            s.setSize(desktop.getWidth(), desktop.getHeight());
            s.show();
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_notificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_notificationActionPerformed
        desktop.removeAll();
        desktop.updateUI();

        try{
            notification n = new notification();
            desktop.add(n);
            desktop.moveToFront(n);
            n.setSize(desktop.getWidth(), desktop.getHeight());
            n.show();
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_notificationActionPerformed

    private void btn_logsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logsActionPerformed
        desktop.removeAll();
        desktop.updateUI();
        try{ 
            activity logs = new activity();
            desktop.add(logs);
            desktop.moveToFront(logs);
            logs.setSize(desktop.getWidth(), desktop.getHeight());
            logs.show();
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_logsActionPerformed

    private void btn_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userActionPerformed
        desktop.removeAll();
        desktop.updateUI();
        try{ 
            user us = new user();
            desktop.add(us);
            desktop.moveToFront(us);
            us.setSize(desktop.getWidth(), desktop.getHeight());
            us.show();
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
                
            }
        });
        
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entry;
    private javax.swing.JButton btn_logs;
    private javax.swing.JButton btn_maintenance;
    private javax.swing.JButton btn_notification;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_transfer;
    private javax.swing.JButton btn_unserviceable;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_user;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
